-- Trigger for APPOINTMENT
CREATE OR REPLACE TRIGGER trg_appointment_updated_at
BEFORE UPDATE ON APPOINTMENT
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Trigger for MEDICAL_RECORD
CREATE OR REPLACE TRIGGER trg_med_record_updated_at
BEFORE UPDATE ON MEDICAL_RECORD
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Trigger for DOCTOR_SCHEDULE
CREATE OR REPLACE TRIGGER trg_doc_schedule_updated_at
BEFORE UPDATE ON DOCTOR_SCHEDULE
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Trigger for PAYMENT_RECORD
CREATE OR REPLACE TRIGGER trg_payment_record_updated_at
BEFORE UPDATE ON PAYMENT_RECORD
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/
