-- ==========================================================================================
-- DEMO 2: MÔ PHỎNG LỖI PHANTOM READ TRÊN BẢNG DOCTOR_SCHEDULE (XẾP TRÙNG PHÒNG TRONG CA)
-- Tệp tin này mô phỏng lỗi tương tranh Phantom Read dẫn đến chèn trùng phòng khám trong cùng một ca.
-- Ngôn ngữ: Oracle PL/SQL.
-- ==========================================================================================

-- ------------------------------------------------------------------------------------------
-- BƯỚC 1: THIẾT LẬP DỮ LIỆU THỬ NGHIỆM (SETUP)
-- Tạo bảng gán ca trực của bác sĩ (chưa có Unique Constraint ở bước đầu).
-- ------------------------------------------------------------------------------------------
CREATE TABLE DOCTOR_SCHEDULE_DEMO (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id VARCHAR2(50),
    room_id VARCHAR2(50),
    schedule_date DATE,
    shift NUMBER(1) -- 1: Ca Sáng, 2: Ca Chiều
);

-- Bảng trống ban đầu, chưa xếp ca trực nào cho bác sĩ X ngày 25/05/2026.
COMMIT;


-- ------------------------------------------------------------------------------------------
-- BƯỚC 2: MÔ PHỎNG LỖI CONCURRENCY (PHANTOM READ / DUPLICATE INSERT RACE)
-- Mở 2 cửa sổ Console song song và chạy tuần tự các lệnh sau:
-- ------------------------------------------------------------------------------------------

/*
============================================================================================
[SESSION 1 - ADMIN A XẾP LỊCH]                        [SESSION 2 - ADMIN B XẾP LỊCH]
============================================================================================

-- Thời điểm T1 (Session 1): Kiểm tra xem Bác sĩ X đã có lịch ca sáng ngày 25/05/2026 chưa.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count 
    FROM DOCTOR_SCHEDULE_DEMO 
    WHERE doctor_id = 'DOCTOR_X' 
      AND schedule_date = TO_DATE('2026-05-25', 'YYYY-MM-DD') 
      AND shift = 1;
      
    DBMS_OUTPUT.PUT_LINE('Session 1 kiểm tra ca trực: Kết quả = ' || v_count);
    
    -- Giả lập trễ mạng
    DBMS_LOCK.SLEEP(5); 
    
    -- Tiến hành xếp phòng ROOM_101 cho bác sĩ X
    INSERT INTO DOCTOR_SCHEDULE_DEMO (doctor_id, room_id, schedule_date, shift)
    VALUES ('DOCTOR_X', 'ROOM_101', TO_DATE('2026-05-25', 'YYYY-MM-DD'), 1);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Session 1 chèn lịch ROOM_101 thành công và COMMIT!');
END;
/

                                                    -- Thời điểm T2 (Session 2 - chạy song song tại giây thứ 1):
                                                    -- Vì S1 chưa commit, S2 quét bảng cũng không thấy dòng nào!
                                                    DECLARE
                                                        v_count NUMBER;
                                                    BEGIN
                                                        SELECT COUNT(*) INTO v_count 
                                                        FROM DOCTOR_SCHEDULE_DEMO 
                                                        WHERE doctor_id = 'DOCTOR_X' 
                                                          AND schedule_date = TO_DATE('2026-05-25', 'YYYY-MM-DD') 
                                                          AND shift = 1;
                                                          
                                                        DBMS_OUTPUT.PUT_LINE('Session 2 kiểm tra ca trực: Kết quả = ' || v_count);
                                                        
                                                        -- Tiến hành xếp phòng ROOM_102 cho bác sĩ X
                                                        -- Lệnh insert này chạy bình thường không bị chặn do không có khóa dòng nào bị chiếm giữ!
                                                        INSERT INTO DOCTOR_SCHEDULE_DEMO (doctor_id, room_id, schedule_date, shift)
                                                        VALUES ('DOCTOR_X', 'ROOM_102', TO_DATE('2026-05-25', 'YYYY-MM-DD'), 1);
                                                        
                                                        COMMIT;
                                                        DBMS_OUTPUT.PUT_LINE('Session 2 chèn lịch ROOM_102 thành công và COMMIT!');
                                                    END;
                                                    /

============================================================================================
--> HẬU QUẢ SAU KHI CẢ HAI COMMIT:
SELECT doctor_id, room_id, TO_CHAR(schedule_date, 'YYYY-MM-DD') as schedule_date, shift FROM DOCTOR_SCHEDULE_DEMO;
--> Kết quả trong DB xuất hiện đồng thời hai lịch trực trùng lặp cho Bác sĩ X:
--> DOCTOR_X | ROOM_101 | 2026-05-25 | 1
--> DOCTOR_X | ROOM_102 | 2026-05-25 | 1 (Sai hoàn toàn nghiệp vụ, 1 bác sĩ không thể ngồi 2 phòng cùng lúc!)
============================================================================================
*/


-- ------------------------------------------------------------------------------------------
-- BƯỚC 3: GIẢI PHÁP KHẮC PHỤC (RÀO CHẮN VẬT LÝ UNIQUE CONSTRAINT)
-- Thiết lập ràng buộc Unique để chặn đứng lỗi chèn trùng lặp từ mức Cơ sở dữ liệu:
-- ------------------------------------------------------------------------------------------

-- Xóa dữ liệu cũ dọn dẹp bảng
DELETE FROM DOCTOR_SCHEDULE_DEMO;
COMMIT;

-- Thêm Unique Constraint ngăn chặn bác sĩ bị xếp trùng ca
ALTER TABLE DOCTOR_SCHEDULE_DEMO 
ADD CONSTRAINT UQ_DOCTOR_SHIFT_DATE UNIQUE (doctor_id, schedule_date, shift);

-- Thêm Unique Constraint ngăn chặn phòng khám bị xếp trùng ca
ALTER TABLE DOCTOR_SCHEDULE_DEMO 
ADD CONSTRAINT UQ_ROOM_SHIFT_DATE UNIQUE (room_id, schedule_date, shift);


-- ------------------------------------------------------------------------------------------
-- BƯỚC 4: CHẠY LẠI THỬ NGHIỆM CONCURRENCY
-- Thử nghiệm xếp ca song song lại khi có Unique Constraint:
-- ------------------------------------------------------------------------------------------

/*
============================================================================================
[SESSION 1 - ADMIN A XẾP LỊCH]                        [SESSION 2 - ADMIN B XẾP LỊCH]
============================================================================================

-- Chạy Session 1 trước:
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM DOCTOR_SCHEDULE_DEMO 
    WHERE doctor_id = 'DOCTOR_X' AND schedule_date = TO_DATE('2026-05-25', 'YYYY-MM-DD') AND shift = 1;
    
    DBMS_LOCK.SLEEP(5); 
    
    INSERT INTO DOCTOR_SCHEDULE_DEMO (doctor_id, room_id, schedule_date, shift)
    VALUES ('DOCTOR_X', 'ROOM_101', TO_DATE('2026-05-25', 'YYYY-MM-DD'), 1);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Session 1 thành công!');
END;
/

                                                    -- Chạy Session 2 song song tại giây thứ 1:
                                                    DECLARE
                                                        v_count NUMBER;
                                                    BEGIN
                                                        SELECT COUNT(*) INTO v_count FROM DOCTOR_SCHEDULE_DEMO 
                                                        WHERE doctor_id = 'DOCTOR_X' AND schedule_date = TO_DATE('2026-05-25', 'YYYY-MM-DD') AND shift = 1;
                                                        
                                                        -- Lệnh chèn này của S2 sẽ báo LỖI VI PHẠM RÀNG BUỘC UNIQUE lập tức 
                                                        -- ngay sau khi Session 1 COMMIT thành công!
                                                        INSERT INTO DOCTOR_SCHEDULE_DEMO (doctor_id, room_id, schedule_date, shift)
                                                        VALUES ('DOCTOR_X', 'ROOM_102', TO_DATE('2026-05-25', 'YYYY-MM-DD'), 1);
                                                        COMMIT;
                                                    EXCEPTION
                                                        WHEN OTHERS THEN
                                                            ROLLBACK;
                                                            DBMS_OUTPUT.PUT_LINE('LỖI CHẶN PHANTOM: Bác sĩ X đã được xếp ca trực này trước đó!');
                                                    END;
                                                    /

============================================================================================
--> KẾT QUẢ TRONG DB: Chỉ duy nhất ca trực ở ROOM_101 của Session 1 được lưu lại.
--> Tầng ứng dụng (backend Java) bắt được DataIntegrityViolationException và phản hồi lỗi chuẩn xác về UI.
============================================================================================
*/


-- ------------------------------------------------------------------------------------------
-- BƯỚC 5: DỌN DẸP DỮ LIỆU DEMO (CLEANUP)
-- ------------------------------------------------------------------------------------------
DROP TABLE DOCTOR_SCHEDULE_DEMO;
