-- ==========================================================================================
-- DEMO 3: MÔ PHỎNG CÁC LỖI RACE CONDITION TRÊN BẢNG MEDICINE (KHO DƯỢC PHẨM)
-- Tệp tin này mô phỏng 3 lỗi tương tranh kho y tế cực kỳ phổ biến:
-- 1. Lost Update gây tồn kho âm.
-- 2. Write Skew giữa Kê đơn và Phát thuốc.
-- 3. Inconsistent Write do thiếu Rollback nguyên tử.
-- Ngôn ngữ: Oracle PL/SQL.
-- ==========================================================================================

-- ------------------------------------------------------------------------------------------
-- BƯỚC 1: THIẾT LẬP DỮ LIỆU THỬ NGHIỆM (SETUP)
-- ------------------------------------------------------------------------------------------
CREATE TABLE MEDICINE_DEMO (
    medicine_id VARCHAR2(50) PRIMARY KEY,
    medicine_name VARCHAR2(100),
    in_stock NUMBER(10)
);

CREATE TABLE PRESCRIPTION_DETAIL_DEMO (
    detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id NUMBER,
    medicine_id VARCHAR2(50),
    quantity NUMBER(5)
);

-- Khởi tạo tồn kho dược phẩm ban đầu
INSERT INTO MEDICINE_DEMO (medicine_id, medicine_name, in_stock) VALUES ('PARACETAMOL', 'Paracetamol 500mg', 100);
INSERT INTO MEDICINE_DEMO (medicine_id, medicine_name, in_stock) VALUES ('AMOXICILLIN', 'Amoxicillin 500mg', 0);
COMMIT;


-- ------------------------------------------------------------------------------------------
-- PHẦN A: MÔ PHỎNG LỖI LOST UPDATE VÀ TỒN KHO ÂM (HAI DƯỢC SĨ CÙNG PHÁT THUỐC SONG SONG)
-- Dược sĩ A phát đơn 60 viên Paracetamol, Dược sĩ B phát đơn 50 viên Paracetamol.
-- ------------------------------------------------------------------------------------------
/*
============================================================================================
[SESSION 1 - DƯỢC SĨ A]                                [SESSION 2 - DƯỢC SĨ B]
============================================================================================

-- S1 chạy trước: Đọc thấy tồn kho là 100
DECLARE
    v_stock NUMBER;
BEGIN
    SELECT in_stock INTO v_stock FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL';
    DBMS_OUTPUT.PUT_LINE('Dược sĩ A kiểm tra kho: ' || v_stock);
    
    DBMS_LOCK.SLEEP(5); -- Giả lập thời gian chuẩn bị thuốc thực tế tại quầy
    
    -- Thực hiện trừ kho 60 viên (100 - 60 = 40) và ghi nhận
    UPDATE MEDICINE_DEMO SET in_stock = v_stock - 60 WHERE medicine_id = 'PARACETAMOL';
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Dược sĩ A trừ kho thành công và COMMIT!');
END;
/

                                                    -- S2 chạy song song tại giây thứ 1: Đọc thấy tồn kho vẫn là 100!
                                                    DECLARE
                                                        v_stock NUMBER;
                                                    BEGIN
                                                        SELECT in_stock INTO v_stock FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL';
                                                        DBMS_OUTPUT.PUT_LINE('Dược sĩ B kiểm tra kho: ' || v_stock);
                                                        
                                                        -- Thực hiện trừ kho 50 viên (100 - 50 = 50) và ghi nhận
                                                        -- Bị chặn hàng đợi do S1 đang chiếm khóa dòng
                                                        UPDATE MEDICINE_DEMO SET in_stock = v_stock - 50 WHERE medicine_id = 'PARACETAMOL';
                                                        COMMIT;
                                                        DBMS_OUTPUT.PUT_LINE('Dược sĩ B trừ kho thành công sau khi S1 commit!');
                                                    END;
                                                    /

============================================================================================
--> HẬU QUẢ: Tồn kho thực tế cấp ra là 110 viên (Kho bị âm -10 viên), nhưng CSDL hiển thị:
SELECT in_stock FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL';
--> Kết quả: 50 viên. Số lượng tồn kho bị sai lệch hoàn toàn, thất thoát 60 viên thuốc!
============================================================================================
*/


-- ------------------------------------------------------------------------------------------
-- PHẦN B: MÔ PHỎNG LỖI WRITE SKEW (BÁC SĨ KÊ ĐƠN & DƯỢC SĨ CẤP PHÁT ĐỒNG THỜI)
-- Trả lại tồn kho Paracetamol là 50 viên.
-- ------------------------------------------------------------------------------------------
UPDATE MEDICINE_DEMO SET in_stock = 50 WHERE medicine_id = 'PARACETAMOL';
COMMIT;

/*
============================================================================================
[SESSION 1 - BÁC SĨ KÊ ĐƠN]                            [SESSION 2 - DƯỢC SĨ CẤP PHÁT]
============================================================================================

-- S1 Bác sĩ kiểm tra tồn kho thấy còn 50 viên -> Đủ để kê đơn 50 viên cho bệnh nhân X
DECLARE
    v_stock NUMBER;
BEGIN
    SELECT in_stock INTO v_stock FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL';
    DBMS_OUTPUT.PUT_LINE('Bác sĩ đọc thấy tồn kho: ' || v_stock);
    
    DBMS_LOCK.SLEEP(5); -- Giả lập bác sĩ đang viết chẩn đoán, dặn dò
    
    -- Chèn thuốc vào đơn
    INSERT INTO PRESCRIPTION_DETAIL_DEMO (prescription_id, medicine_id, quantity)
    VALUES (101, 'PARACETAMOL', 50);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Bác sĩ kê đơn thành công và COMMIT!');
END;
/

                                                    -- S2 Dược sĩ cấp phát 50 viên cho đơn cũ
                                                    DECLARE
                                                        v_stock NUMBER;
                                                    BEGIN
                                                        SELECT in_stock INTO v_stock FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL';
                                                        DBMS_OUTPUT.PUT_LINE('Dược sĩ đọc thấy tồn kho: ' || v_stock);
                                                        
                                                        -- Trừ kho trực tiếp
                                                        UPDATE MEDICINE_DEMO SET in_stock = v_stock - 50 WHERE medicine_id = 'PARACETAMOL';
                                                        COMMIT;
                                                        DBMS_OUTPUT.PUT_LINE('Dược sĩ phát thuốc thành công và COMMIT!');
                                                    END;
                                                    /

============================================================================================
--> HẬU QUẢ WRITE SKEW: Cả 2 giao dịch thành công. Nhưng đơn mới kê của bệnh nhân X (50 viên)
--> hoàn toàn không còn một hạt thuốc nào trong kho thực tế để phát do Dược sĩ đã xuất hết trước đó.
============================================================================================
*/


-- ------------------------------------------------------------------------------------------
-- PHẦN C: MÔ PHỎNG LỖI MẤT NHẤT QUÁN (INCONSISTENT WRITE DO THIẾU TRANSACTION ATOMIC)
-- Đơn thuốc yêu cầu: Paracetamol (trừ 10 viên) và Amoxicillin (trừ 10 viên nhưng đã hết hàng).
-- Đoạn mã giả lập luồng ghi tuần tự không quản lý Transaction nguyên tử:
-- ------------------------------------------------------------------------------------------
UPDATE MEDICINE_DEMO SET in_stock = 10 WHERE medicine_id = 'PARACETAMOL';
UPDATE MEDICINE_DEMO SET in_stock = 0 WHERE medicine_id = 'AMOXICILLIN';
COMMIT;

DECLARE
    v_stock NUMBER;
BEGIN
    -- 1. Trừ thuốc thứ nhất (Paracetamol) thành công
    UPDATE MEDICINE_DEMO SET in_stock = in_stock - 10 WHERE medicine_id = 'PARACETAMOL';
    
    -- 2. Kiểm tra thuốc thứ hai (Amoxicillin)
    SELECT in_stock INTO v_stock FROM MEDICINE_DEMO WHERE medicine_id = 'AMOXICILLIN';
    
    IF v_stock < 10 THEN
        -- Báo lỗi thiếu thuốc
        RAISE_APPLICATION_ERROR(-20201, 'Hết thuốc Amoxicillin trong kho!');
    ELSE
        UPDATE MEDICINE_DEMO SET in_stock = in_stock - 10 WHERE medicine_id = 'AMOXICILLIN';
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        -- !!! LỖI LẬP TRÌNH: KẾT THÚC TIẾN TRÌNH THIẾU AN TOÀN MÀ KHÔNG GỌI ROLLBACK !!!
        DBMS_OUTPUT.PUT_LINE('Giao dịch phát sinh lỗi: ' || SQLERRM);
        -- Lệnh COMMIT dưới đây sẽ lưu vĩnh viễn thay đổi trừ thuốc ở mục 1 vào Database!
        COMMIT; 
END;
/

-- Kiểm tra kết quả trong DB sau khi lỗi xảy ra:
SELECT medicine_id, in_stock FROM MEDICINE_DEMO;
--> Paracetamol: 0 (Bị trừ oan mất 10 viên trong khi đơn thuốc thất bại, bệnh nhân chưa nhận thuốc).
--> Amoxicillin: 0
--> Dữ liệu kho bị bất nhất nghiêm trọng!


-- ------------------------------------------------------------------------------------------
-- BƯỚC 4: GIẢI PHÁP TOÀN DIỆN (TRANSACTION ATOMIC + PESSIMISTIC LOCK SELECT FOR UPDATE)
-- Chạy đoạn mã này để thấy cách hệ thống giải quyết triệt để 3 vấn đề tương tranh kho:
-- ------------------------------------------------------------------------------------------

-- Phục hồi lại dữ liệu thử nghiệm
UPDATE MEDICINE_DEMO SET in_stock = 100 WHERE medicine_id = 'PARACETAMOL';
UPDATE MEDICINE_DEMO SET in_stock = 0 WHERE medicine_id = 'AMOXICILLIN';
DELETE FROM PRESCRIPTION_DETAIL_DEMO;
COMMIT;

DECLARE
    v_req_paracel NUMBER := 60;
    v_req_amox NUMBER := 10;
    v_stock_paracel NUMBER;
    v_stock_amox NUMBER;
BEGIN
    -- 1. THIẾT LẬP KHÓA BI QUAN TRÊN TẤT CẢ CÁC LÔ/DÒNG THUỐC CẦN SỬ DỤNG
    -- Ngăn chặn toàn bộ các luồng kê đơn hay phát thuốc khác đọc/sửa các loại thuốc này
    SELECT in_stock INTO v_stock_paracel FROM MEDICINE_DEMO WHERE medicine_id = 'PARACETAMOL' FOR UPDATE;
    SELECT in_stock INTO v_stock_amox FROM MEDICINE_DEMO WHERE medicine_id = 'AMOXICILLIN' FOR UPDATE;
    
    -- 2. KIỂM TRA CHẶT CHẼ TRƯỚC KHI GHI NHẬN
    IF v_stock_paracel < v_req_paracel THEN
        RAISE_APPLICATION_ERROR(-20202, 'Dược phẩm Paracetamol không đủ tồn kho khả dụng!');
    END IF;
    
    IF v_stock_amox < v_req_amox THEN
        RAISE_APPLICATION_ERROR(-20203, 'Dược phẩm Amoxicillin không đủ tồn kho khả dụng!');
    END IF;
    
    -- 3. NẾU ĐỦ, TIẾN HÀNH KHẤU TRỪ KHO ĐỒNG BỘ
    UPDATE MEDICINE_DEMO SET in_stock = in_stock - v_req_paracel WHERE medicine_id = 'PARACETAMOL';
    UPDATE MEDICINE_DEMO SET in_stock = in_stock - v_req_amox WHERE medicine_id = 'AMOXICILLIN';
    
    -- Ghi nhận thành công
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Toàn bộ giao dịch cấp phát thành công tốt đẹp!');
EXCEPTION
    WHEN OTHERS THEN
        -- ĐẢM BẢO TÍNH NGUYÊN TỬ (ATOMICITY): HOÀN TÁC TOÀN BỘ NẾU CÓ BẤT KỲ LỖI NÀO
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Cấp phát thất bại. Giao dịch đã ROLLBACK an toàn! Lỗi: ' || SQLERRM);
END;
/


-- ------------------------------------------------------------------------------------------
-- BƯỚC 5: DỌN DẸP DỮ LIỆU DEMO (CLEANUP)
-- ------------------------------------------------------------------------------------------
DROP TABLE PRESCRIPTION_DETAIL_DEMO;
DROP TABLE MEDICINE_DEMO;
