CREATE TABLE medicine_lot (
    medicine_lot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id NUMBER NOT NULL,
    lot_number VARCHAR2(100) NOT NULL,
    manufacturing_date DATE,
    expiry_date DATE NOT NULL,
    quantity NUMBER DEFAULT 0 NOT NULL,
    import_price NUMBER(15, 2),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,

    CONSTRAINT fk_medicine_lot_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicine (medicine_id),

    CONSTRAINT uk_medicine_lot_medicine_lot_number
        UNIQUE (medicine_id, lot_number),

    CONSTRAINT chk_medicine_lot_quantity
        CHECK (quantity >= 0),

    CONSTRAINT chk_medicine_lot_import_price
        CHECK (import_price IS NULL OR import_price >= 0),

    CONSTRAINT chk_medicine_lot_expiry_date
        CHECK (manufacturing_date IS NULL OR expiry_date > manufacturing_date)
);