BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE medicine CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE medicine (
    medicine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR2(200) NOT NULL,
    active_ingredient VARCHAR2(200),
    unit VARCHAR2(50) NOT NULL,
    description VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1 NOT NULL
);

ALTER TABLE medicine
ADD CONSTRAINT uk_medicine_name UNIQUE (medicine_name);