BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE prescription_detail CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE prescription CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    med_record_id NUMBER NOT NULL,
    note CLOB,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_prescription_medical_record
        FOREIGN KEY (med_record_id)
        REFERENCES medical_record (med_record_id),

    CONSTRAINT uk_prescription_medical_record
        UNIQUE (med_record_id)
);

CREATE TABLE prescription_detail (
    prescription_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id NUMBER NOT NULL,
    medicine_id NUMBER NOT NULL,
    dosage VARCHAR2(100) NOT NULL,
    frequency VARCHAR2(100) NOT NULL,
    duration VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    instruction VARCHAR2(500),

    CONSTRAINT fk_prescription_detail_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES prescription (prescription_id),

    CONSTRAINT fk_prescription_detail_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicine (medicine_id),

    CONSTRAINT chk_prescription_detail_quantity
        CHECK (quantity >= 1)
);